on:
  push:
    branches:
      - master
name: Update GitHub Pages
jobs:
  updatePages:
    name: Update GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Static Website
        run: npm run build
    
      - name: Push to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          full_commit_message: Update Pages for ${{ github.event.head_commit.id }}
